# Generated by Django 2.1 on 2018-08-19 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('plan_type', models.CharField(choices=[('FREE', 'Basic Plan'), ('MONTHLY_PLAN', 'Monthly Plan ($29/Mo)'), ('ANNUAL_PLAN', 'Annual Plan ($299/Yr)')], default='FREE', max_length=15)),
                ('initiated_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('stripe_customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='suscriptions.Customer')),
            ],
        ),
    ]
